#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define WIN_WIDTH 1024
#define WIN_HEIGHT 768

#define MAX_PLAYERS 10
#define MAX_BUFFER 512

#define PALA_WIDTH 20
#define PALA_HEIGHT 100
#define COLOR_PALA 0xFFFFFF
#define COLOR_BOLA 0xFFFFFF

#define BOLA_SIZE 10

#endif // CONSTANTS_H_INCLUDED
